dist: xenial
language: java
sudo: false
jdk: openjdk11
install: true
script:
  - mvn clean verify sonar:sonar -P sonar -Dsonar.organization=${SONAR_ORGANIZATION} -Dsonar.projectKey=${SONAR_PROJECT_KEY} -Dsonar.login=${SONAR_TOKEN}
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar/cache
after_success:
  - bash <(curl -s https://codecov.io/bash)
