dist: xenial
language: java
sudo: false
jdk: openjdk11
install: true
addons:
  sonarcloud:
    organization: "cleysonph"
    token: ${SONAR_TOKEN}
script:
  - mvn clean verify sonar:sonar -P sonar -Dsonar.projectKey=CleysonPH_bookstoremanager
cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache
